### PR TITLE
More Technical Info from CPE

### PR DESCRIPTION
**Pull request by KryoStoffer**
Hi

I am working on transforming what is available from our various fiber CPEs into on-api format, but ran into some minor issues.

There is more useful information from SFP available in most cases, I have added some of the most common fields.

Some CPE's include multicast MAC's when they return MAC forwarding table, this could be useful in troubleshooting multicast issues, but to allow them in the list, the port field will have to allow a list, this change is not backwards compatible so might be too invasive.

Some CPE's unfortunately does not provide octet/byte counters, so instead of being blind I propose adding the possibility to include packet counters.

br.

Kristoffer Larsen
kri@telia.net

### CODE REVIEW

**Comment by jstenmark** [comment]
Hello Kristoffer, thanks for the PR!

Looks good, I'm only wondering if it's maybe better to put this mc mac data under it's own endpoint.
Improved ipv6 support is one of the goals of to the next major release.

We are currently having a final round of fixes before next release.

**Comment by KryoStoffer** [comment]
The CPE's it self does not tell weather the mac addresses are multicast or not, we can kind of figure it out by learning the parser the know ranges for multicast addresses or assume that it is a multicast address if it exists on multiple ports.

I do like the idea of separating them in the presentation, but don't like adding too much non transparent conversion of data from the CPE towards the on-api. So there is pros and cons on both parts.

Just tell me what you prefer and I will adjust the pull request.

br.

Kristoffer Larsen

**Comment by jstenmark** [comment]
I prefer you leave the multicast macs commit out for now and we should be able to fit the PR in this release, let me look into it.

And lets look into a solid implementation of multicast mac support for the next version.

**Comment by KryoStoffer** [comment]
Ok I have reverted the commit allowing multiple ports for a MAC.

**Pull request merged**
